dist: trusty

services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t mmysql-simple-db .
      - docker images
      - docker tag mysql-simple-db $DOCKER_USERNAME/mysql-simple-db:1.${TRAVIS_BUILD_NUMBER}
      - docker push $DOCKER_USERNAME/mysql-simple-db:1.${TRAVIS_BUILD_NUMBER}